/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'volunteerCount' : bigint,
  'storyCount' : bigint,
  'galleryCount' : bigint,
  'eventCount' : bigint,
  'blogCount' : bigint,
}
export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'date' : string,
  'published' : boolean,
  'author' : string,
  'imageUrl' : string,
  'excerpt' : string,
  'category' : string,
}
export interface ContactSubmission {
  'id' : bigint,
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface Event {
  'id' : bigint,
  'status' : string,
  'title' : string,
  'date' : string,
  'description' : string,
  'imageUrl' : string,
  'registrationsOpen' : boolean,
  'category' : string,
  'location' : string,
}
export interface EventRegistration {
  'id' : bigint,
  'eventId' : bigint,
  'name' : string,
  'email' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface GalleryImage {
  'id' : bigint,
  'title' : string,
  'date' : string,
  'description' : string,
  'imageKey' : string,
  'category' : string,
  'location' : string,
  'uploadedAt' : bigint,
}
export interface InternshipApplication {
  'id' : bigint,
  'area' : string,
  'city' : string,
  'name' : string,
  'email' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface NewsletterSignup {
  'id' : bigint,
  'email' : string,
  'timestamp' : bigint,
}
export interface PartnerInquiry {
  'id' : bigint,
  'contactPerson' : string,
  'email' : string,
  'timestamp' : bigint,
  'partnershipNature' : string,
  'organization' : string,
}
export interface SuccessStory {
  'id' : bigint,
  'title' : string,
  'storyText' : string,
  'beneficiaryName' : string,
  'date' : string,
  'imageUrl' : string,
  'location' : string,
}
export interface VolunteerApplication {
  'id' : bigint,
  'city' : string,
  'name' : string,
  'email' : string,
  'availability' : string,
  'timestamp' : bigint,
  'phone' : string,
  'skills' : string,
}
export interface _SERVICE {
  'addBlogPost' : ActorMethod<
    [string, string, string, string, string, string, string],
    bigint
  >,
  'addEvent' : ActorMethod<
    [string, string, string, string, string, string, string, boolean],
    bigint
  >,
  'addGalleryImage' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'addSuccessStory' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'applyInternship' : ActorMethod<
    [string, string, string, string, string],
    bigint
  >,
  'applyVolunteer' : ActorMethod<
    [string, string, string, string, string, string],
    bigint
  >,
  'deleteBlogPost' : ActorMethod<[bigint], boolean>,
  'deleteEvent' : ActorMethod<[bigint], boolean>,
  'deleteGalleryImage' : ActorMethod<[bigint], boolean>,
  'deleteSuccessStory' : ActorMethod<[bigint], boolean>,
  'getAdminSettings' : ActorMethod<
    [],
    {
      'chairpersonPhotoKey' : [] | [string],
      'adminPrincipals' : Array<Principal>,
      'razorpayKeyId' : [] | [string],
      'treasurerPhotoKey' : [] | [string],
    }
  >,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getBlogPostsByCategory' : ActorMethod<[string], Array<BlogPost>>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getEventRegistrations' : ActorMethod<[bigint], Array<EventRegistration>>,
  'getGalleryImagesByCategory' : ActorMethod<[string], Array<GalleryImage>>,
  'getInternshipApplications' : ActorMethod<[], Array<InternshipApplication>>,
  'getNewsletterSignups' : ActorMethod<[], Array<NewsletterSignup>>,
  'getPartnerInquiries' : ActorMethod<[], Array<PartnerInquiry>>,
  'getPastEvents' : ActorMethod<[], Array<Event>>,
  'getUpcomingEvents' : ActorMethod<[], Array<Event>>,
  'getVolunteerApplications' : ActorMethod<[], Array<VolunteerApplication>>,
  'listBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'listEvents' : ActorMethod<[], Array<Event>>,
  'listGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'listSuccessStories' : ActorMethod<[], Array<SuccessStory>>,
  'registerForEvent' : ActorMethod<[bigint, string, string, string], bigint>,
  'submitContact' : ActorMethod<[string, string, string, string], bigint>,
  'submitPartnerInquiry' : ActorMethod<
    [string, string, string, string],
    bigint
  >,
  'subscribeNewsletter' : ActorMethod<
    [string],
    { 'ok' : bigint } |
      { 'err' : string }
  >,
  'updateAdminPrincipals' : ActorMethod<
    [Array<Principal>],
    { 'ok' : boolean, 'err' : [] | [string] }
  >,
  'updateBlogPost' : ActorMethod<
    [bigint, string, string, string, string, string, string, string, boolean],
    boolean
  >,
  'updateEvent' : ActorMethod<
    [bigint, string, string, string, string, string, string, string, boolean],
    boolean
  >,
  'updateGalleryImage' : ActorMethod<
    [bigint, string, string, string, string, string],
    boolean
  >,
  'updateRazorpayKeyId' : ActorMethod<
    [string],
    { 'ok' : boolean, 'err' : [] | [string] }
  >,
  'updateSuccessStory' : ActorMethod<
    [bigint, string, string, string, string, string, string],
    boolean
  >,
  'updateTeamPhotos' : ActorMethod<
    [[] | [string], [] | [string]],
    { 'ok' : boolean, 'err' : [] | [string] }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];