/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AdminStats = IDL.Record({
  'volunteerCount' : IDL.Nat,
  'storyCount' : IDL.Nat,
  'galleryCount' : IDL.Nat,
  'eventCount' : IDL.Nat,
  'blogCount' : IDL.Nat,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Text,
  'published' : IDL.Bool,
  'author' : IDL.Text,
  'imageUrl' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const ContactSubmission = IDL.Record({
  'id' : IDL.Nat,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const EventRegistration = IDL.Record({
  'id' : IDL.Nat,
  'eventId' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const GalleryImage = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'imageKey' : IDL.Text,
  'category' : IDL.Text,
  'location' : IDL.Text,
  'uploadedAt' : IDL.Int,
});
export const InternshipApplication = IDL.Record({
  'id' : IDL.Nat,
  'area' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
});
export const NewsletterSignup = IDL.Record({
  'id' : IDL.Nat,
  'email' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const PartnerInquiry = IDL.Record({
  'id' : IDL.Nat,
  'contactPerson' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : IDL.Int,
  'partnershipNature' : IDL.Text,
  'organization' : IDL.Text,
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'registrationsOpen' : IDL.Bool,
  'category' : IDL.Text,
  'location' : IDL.Text,
});
export const ProgramContent = IDL.Record({
  'id' : IDL.Text,
  'stat1Label' : IDL.Text,
  'tagline' : IDL.Text,
  'stat2Value' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'heroImage' : IDL.Text,
  'stat2Label' : IDL.Text,
  'updatedAt' : IDL.Int,
  'stat3Value' : IDL.Text,
  'howItWorks' : IDL.Vec(IDL.Text),
  'stat1Value' : IDL.Text,
  'stat3Label' : IDL.Text,
});
export const VolunteerApplication = IDL.Record({
  'id' : IDL.Nat,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'availability' : IDL.Text,
  'timestamp' : IDL.Int,
  'phone' : IDL.Text,
  'skills' : IDL.Text,
});
export const SuccessStory = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'storyText' : IDL.Text,
  'beneficiaryName' : IDL.Text,
  'date' : IDL.Text,
  'imageUrl' : IDL.Text,
  'location' : IDL.Text,
  'program' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addEvent' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [IDL.Nat],
      [],
    ),
  'addGalleryImage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addSuccessStory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'applyInternship' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'applyVolunteer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteBlogPost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteEvent' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteGalleryImage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'deleteSuccessStory' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAdminSettings' : IDL.Func(
      [],
      [
        IDL.Record({
          'chairpersonPhotoKey' : IDL.Opt(IDL.Text),
          'adminPrincipals' : IDL.Vec(IDL.Principal),
          'razorpayKeyId' : IDL.Opt(IDL.Text),
          'treasurerPhotoKey' : IDL.Opt(IDL.Text),
          'secretaryPhotoKey' : IDL.Opt(IDL.Text),
          'ngoStats' : IDL.Record({
            'districtsCovered' : IDL.Text,
            'villagesCovered' : IDL.Text,
            'volunteers' : IDL.Text,
            'treesPlanted' : IDL.Text,
            'acresConserved' : IDL.Text,
            'panchayatsCovered' : IDL.Text,
            'householdsCovered' : IDL.Text,
            'farmersTrained' : IDL.Text,
          }),
        }),
      ],
      ['query'],
    ),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getBlogPostsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BlogPost)],
      ['query'],
    ),
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getEventRegistrations' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(EventRegistration)],
      ['query'],
    ),
  'getGalleryImagesByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(GalleryImage)],
      ['query'],
    ),
  'getInternshipApplications' : IDL.Func(
      [],
      [IDL.Vec(InternshipApplication)],
      ['query'],
    ),
  'getNewsletterSignups' : IDL.Func([], [IDL.Vec(NewsletterSignup)], ['query']),
  'getPartnerInquiries' : IDL.Func([], [IDL.Vec(PartnerInquiry)], ['query']),
  'getPastEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getProgramContent' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ProgramContent)],
      ['query'],
    ),
  'getUpcomingEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getVolunteerApplications' : IDL.Func(
      [],
      [IDL.Vec(VolunteerApplication)],
      ['query'],
    ),
  'listBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'listEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'listGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'listPrograms' : IDL.Func([], [IDL.Vec(ProgramContent)], ['query']),
  'listSuccessStories' : IDL.Func([], [IDL.Vec(SuccessStory)], ['query']),
  'listSuccessStoriesByProgram' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SuccessStory)],
      ['query'],
    ),
  'registerForEvent' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'submitPartnerInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'subscribeNewsletter' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
      [],
    ),
  'updateAdminPrincipals' : IDL.Func(
      [IDL.Vec(IDL.Principal)],
      [IDL.Record({ 'ok' : IDL.Bool, 'err' : IDL.Opt(IDL.Text) })],
      [],
    ),
  'updateBlogPost' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [IDL.Bool],
      [],
    ),
  'updateEvent' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
      ],
      [IDL.Bool],
      [],
    ),
  'updateGalleryImage' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'updateNgoStats' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Record({ 'ok' : IDL.Bool, 'err' : IDL.Opt(IDL.Text) })],
      [],
    ),
  'updateRazorpayKeyId' : IDL.Func(
      [IDL.Text],
      [IDL.Record({ 'ok' : IDL.Bool, 'err' : IDL.Opt(IDL.Text) })],
      [],
    ),
  'updateSuccessStory' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Bool],
      [],
    ),
  'updateTeamPhotos' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Record({ 'ok' : IDL.Bool, 'err' : IDL.Opt(IDL.Text) })],
      [],
    ),
  'upsertProgramContent' : IDL.Func(
      [ProgramContent],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AdminStats = IDL.Record({
    'volunteerCount' : IDL.Nat,
    'storyCount' : IDL.Nat,
    'galleryCount' : IDL.Nat,
    'eventCount' : IDL.Nat,
    'blogCount' : IDL.Nat,
  });
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Text,
    'published' : IDL.Bool,
    'author' : IDL.Text,
    'imageUrl' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const ContactSubmission = IDL.Record({
    'id' : IDL.Nat,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const EventRegistration = IDL.Record({
    'id' : IDL.Nat,
    'eventId' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const GalleryImage = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'imageKey' : IDL.Text,
    'category' : IDL.Text,
    'location' : IDL.Text,
    'uploadedAt' : IDL.Int,
  });
  const InternshipApplication = IDL.Record({
    'id' : IDL.Nat,
    'area' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
  });
  const NewsletterSignup = IDL.Record({
    'id' : IDL.Nat,
    'email' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const PartnerInquiry = IDL.Record({
    'id' : IDL.Nat,
    'contactPerson' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : IDL.Int,
    'partnershipNature' : IDL.Text,
    'organization' : IDL.Text,
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'registrationsOpen' : IDL.Bool,
    'category' : IDL.Text,
    'location' : IDL.Text,
  });
  const ProgramContent = IDL.Record({
    'id' : IDL.Text,
    'stat1Label' : IDL.Text,
    'tagline' : IDL.Text,
    'stat2Value' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'heroImage' : IDL.Text,
    'stat2Label' : IDL.Text,
    'updatedAt' : IDL.Int,
    'stat3Value' : IDL.Text,
    'howItWorks' : IDL.Vec(IDL.Text),
    'stat1Value' : IDL.Text,
    'stat3Label' : IDL.Text,
  });
  const VolunteerApplication = IDL.Record({
    'id' : IDL.Nat,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'availability' : IDL.Text,
    'timestamp' : IDL.Int,
    'phone' : IDL.Text,
    'skills' : IDL.Text,
  });
  const SuccessStory = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'storyText' : IDL.Text,
    'beneficiaryName' : IDL.Text,
    'date' : IDL.Text,
    'imageUrl' : IDL.Text,
    'location' : IDL.Text,
    'program' : IDL.Text,
  });
  
  return IDL.Service({
    'addBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addEvent' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [IDL.Nat],
        [],
      ),
    'addGalleryImage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addSuccessStory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'applyInternship' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'applyVolunteer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteBlogPost' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteEvent' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteGalleryImage' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'deleteSuccessStory' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAdminSettings' : IDL.Func(
        [],
        [
          IDL.Record({
            'chairpersonPhotoKey' : IDL.Opt(IDL.Text),
            'adminPrincipals' : IDL.Vec(IDL.Principal),
            'razorpayKeyId' : IDL.Opt(IDL.Text),
            'treasurerPhotoKey' : IDL.Opt(IDL.Text),
            'secretaryPhotoKey' : IDL.Opt(IDL.Text),
            'ngoStats' : IDL.Record({
              'districtsCovered' : IDL.Text,
              'villagesCovered' : IDL.Text,
              'volunteers' : IDL.Text,
              'treesPlanted' : IDL.Text,
              'acresConserved' : IDL.Text,
              'panchayatsCovered' : IDL.Text,
              'householdsCovered' : IDL.Text,
              'farmersTrained' : IDL.Text,
            }),
          }),
        ],
        ['query'],
      ),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getBlogPostsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BlogPost)],
        ['query'],
      ),
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getEventRegistrations' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(EventRegistration)],
        ['query'],
      ),
    'getGalleryImagesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(GalleryImage)],
        ['query'],
      ),
    'getInternshipApplications' : IDL.Func(
        [],
        [IDL.Vec(InternshipApplication)],
        ['query'],
      ),
    'getNewsletterSignups' : IDL.Func(
        [],
        [IDL.Vec(NewsletterSignup)],
        ['query'],
      ),
    'getPartnerInquiries' : IDL.Func([], [IDL.Vec(PartnerInquiry)], ['query']),
    'getPastEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getProgramContent' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ProgramContent)],
        ['query'],
      ),
    'getUpcomingEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getVolunteerApplications' : IDL.Func(
        [],
        [IDL.Vec(VolunteerApplication)],
        ['query'],
      ),
    'listBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'listEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'listGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'listPrograms' : IDL.Func([], [IDL.Vec(ProgramContent)], ['query']),
    'listSuccessStories' : IDL.Func([], [IDL.Vec(SuccessStory)], ['query']),
    'listSuccessStoriesByProgram' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SuccessStory)],
        ['query'],
      ),
    'registerForEvent' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'submitPartnerInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'subscribeNewsletter' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text })],
        [],
      ),
    'updateAdminPrincipals' : IDL.Func(
        [IDL.Vec(IDL.Principal)],
        [IDL.Record({ 'ok' : IDL.Bool, 'err' : IDL.Opt(IDL.Text) })],
        [],
      ),
    'updateBlogPost' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [IDL.Bool],
        [],
      ),
    'updateEvent' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
        ],
        [IDL.Bool],
        [],
      ),
    'updateGalleryImage' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'updateNgoStats' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Record({ 'ok' : IDL.Bool, 'err' : IDL.Opt(IDL.Text) })],
        [],
      ),
    'updateRazorpayKeyId' : IDL.Func(
        [IDL.Text],
        [IDL.Record({ 'ok' : IDL.Bool, 'err' : IDL.Opt(IDL.Text) })],
        [],
      ),
    'updateSuccessStory' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Bool],
        [],
      ),
    'updateTeamPhotos' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Record({ 'ok' : IDL.Bool, 'err' : IDL.Opt(IDL.Text) })],
        [],
      ),
    'upsertProgramContent' : IDL.Func(
        [ProgramContent],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };