/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BlogPost {
    id: bigint;
    title: string;
    content: string;
    date: string;
    published: boolean;
    author: string;
    imageUrl: string;
    excerpt: string;
    category: string;
}
export interface SuccessStory {
    id: bigint;
    title: string;
    storyText: string;
    beneficiaryName: string;
    date: string;
    imageUrl: string;
    location: string;
}
export interface VolunteerApplication {
    id: bigint;
    city: string;
    name: string;
    email: string;
    availability: string;
    timestamp: bigint;
    phone: string;
    skills: string;
}
export interface AdminStats {
    volunteerCount: bigint;
    storyCount: bigint;
    galleryCount: bigint;
    eventCount: bigint;
    blogCount: bigint;
}
export interface PartnerInquiry {
    id: bigint;
    contactPerson: string;
    email: string;
    timestamp: bigint;
    partnershipNature: string;
    organization: string;
}
export interface GalleryImage {
    id: bigint;
    title: string;
    date: string;
    description: string;
    imageKey: string;
    category: string;
    location: string;
    uploadedAt: bigint;
}
export interface Event {
    id: bigint;
    status: string;
    title: string;
    date: string;
    description: string;
    imageUrl: string;
    registrationsOpen: boolean;
    category: string;
    location: string;
}
export interface ContactSubmission {
    id: bigint;
    subject: string;
    name: string;
    email: string;
    message: string;
    timestamp: bigint;
}
export interface EventRegistration {
    id: bigint;
    eventId: bigint;
    name: string;
    email: string;
    timestamp: bigint;
    phone: string;
}
export interface InternshipApplication {
    id: bigint;
    area: string;
    city: string;
    name: string;
    email: string;
    timestamp: bigint;
    phone: string;
}
export interface NewsletterSignup {
    id: bigint;
    email: string;
    timestamp: bigint;
}
export interface backendInterface {
    addBlogPost(title: string, excerpt: string, content: string, category: string, date: string, imageUrl: string, author: string): Promise<bigint>;
    addEvent(title: string, description: string, date: string, location: string, category: string, imageUrl: string, status: string, registrationsOpen: boolean): Promise<bigint>;
    addGalleryImage(title: string, description: string, category: string, date: string, location: string, imageKey: string): Promise<bigint>;
    addSuccessStory(title: string, beneficiaryName: string, location: string, storyText: string, imageUrl: string, date: string): Promise<bigint>;
    applyInternship(name: string, email: string, phone: string, city: string, area: string): Promise<bigint>;
    applyVolunteer(name: string, email: string, phone: string, city: string, skills: string, availability: string): Promise<bigint>;
    deleteBlogPost(id: bigint): Promise<boolean>;
    deleteEvent(id: bigint): Promise<boolean>;
    deleteGalleryImage(id: bigint): Promise<boolean>;
    deleteSuccessStory(id: bigint): Promise<boolean>;
    getAdminSettings(): Promise<{
        chairpersonPhotoKey?: string;
        adminPrincipals: Array<Principal>;
        razorpayKeyId?: string;
        treasurerPhotoKey?: string;
    }>;
    getAdminStats(): Promise<AdminStats>;
    getAllBlogPosts(): Promise<Array<BlogPost>>;
    getBlogPostsByCategory(category: string): Promise<Array<BlogPost>>;
    getContactSubmissions(): Promise<Array<ContactSubmission>>;
    getEventRegistrations(eventId: bigint): Promise<Array<EventRegistration>>;
    getGalleryImagesByCategory(category: string): Promise<Array<GalleryImage>>;
    getInternshipApplications(): Promise<Array<InternshipApplication>>;
    getNewsletterSignups(): Promise<Array<NewsletterSignup>>;
    getPartnerInquiries(): Promise<Array<PartnerInquiry>>;
    getPastEvents(): Promise<Array<Event>>;
    getUpcomingEvents(): Promise<Array<Event>>;
    getVolunteerApplications(): Promise<Array<VolunteerApplication>>;
    listBlogPosts(): Promise<Array<BlogPost>>;
    listEvents(): Promise<Array<Event>>;
    listGalleryImages(): Promise<Array<GalleryImage>>;
    listSuccessStories(): Promise<Array<SuccessStory>>;
    registerForEvent(eventId: bigint, name: string, email: string, phone: string): Promise<bigint>;
    submitContact(name: string, email: string, subject: string, message: string): Promise<bigint>;
    submitPartnerInquiry(organization: string, contactPerson: string, email: string, partnershipNature: string): Promise<bigint>;
    subscribeNewsletter(email: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }>;
    updateAdminPrincipals(principals: Array<Principal>): Promise<{
        ok: boolean;
        err?: string;
    }>;
    updateBlogPost(id: bigint, title: string, excerpt: string, content: string, category: string, date: string, imageUrl: string, author: string, published: boolean): Promise<boolean>;
    updateEvent(id: bigint, title: string, description: string, date: string, location: string, category: string, imageUrl: string, status: string, registrationsOpen: boolean): Promise<boolean>;
    updateGalleryImage(id: bigint, title: string, description: string, category: string, date: string, location: string): Promise<boolean>;
    updateRazorpayKeyId(keyId: string): Promise<{
        ok: boolean;
        err?: string;
    }>;
    updateSuccessStory(id: bigint, title: string, beneficiaryName: string, location: string, storyText: string, imageUrl: string, date: string): Promise<boolean>;
    updateTeamPhotos(chairpersonKey: string | null, treasurerKey: string | null): Promise<{
        ok: boolean;
        err?: string;
    }>;
}
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addBlogPost(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addBlogPost(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBlogPost(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async addEvent(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addEvent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEvent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
            return result;
        }
    }
    async addGalleryImage(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryImage(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryImage(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addSuccessStory(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addSuccessStory(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSuccessStory(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async applyInternship(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.applyInternship(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyInternship(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async applyVolunteer(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.applyVolunteer(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyVolunteer(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async deleteBlogPost(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogPost(arg0);
            return result;
        }
    }
    async deleteEvent(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEvent(arg0);
            return result;
        }
    }
    async deleteGalleryImage(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGalleryImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGalleryImage(arg0);
            return result;
        }
    }
    async deleteSuccessStory(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSuccessStory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSuccessStory(arg0);
            return result;
        }
    }
    async getAdminSettings(): Promise<{
        chairpersonPhotoKey?: string;
        adminPrincipals: Array<Principal>;
        razorpayKeyId?: string;
        treasurerPhotoKey?: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminSettings();
                return from_candid_record_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminSettings();
            return from_candid_record_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAdminStats(): Promise<AdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats();
            return result;
        }
    }
    async getAllBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBlogPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBlogPosts();
            return result;
        }
    }
    async getBlogPostsByCategory(arg0: string): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPostsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPostsByCategory(arg0);
            return result;
        }
    }
    async getContactSubmissions(): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactSubmissions();
            return result;
        }
    }
    async getEventRegistrations(arg0: bigint): Promise<Array<EventRegistration>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEventRegistrations(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEventRegistrations(arg0);
            return result;
        }
    }
    async getGalleryImagesByCategory(arg0: string): Promise<Array<GalleryImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryImagesByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryImagesByCategory(arg0);
            return result;
        }
    }
    async getInternshipApplications(): Promise<Array<InternshipApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInternshipApplications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInternshipApplications();
            return result;
        }
    }
    async getNewsletterSignups(): Promise<Array<NewsletterSignup>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsletterSignups();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsletterSignups();
            return result;
        }
    }
    async getPartnerInquiries(): Promise<Array<PartnerInquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPartnerInquiries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPartnerInquiries();
            return result;
        }
    }
    async getPastEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPastEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPastEvents();
            return result;
        }
    }
    async getUpcomingEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUpcomingEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUpcomingEvents();
            return result;
        }
    }
    async getVolunteerApplications(): Promise<Array<VolunteerApplication>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVolunteerApplications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVolunteerApplications();
            return result;
        }
    }
    async listBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.listBlogPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listBlogPosts();
            return result;
        }
    }
    async listEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEvents();
            return result;
        }
    }
    async listGalleryImages(): Promise<Array<GalleryImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.listGalleryImages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGalleryImages();
            return result;
        }
    }
    async listSuccessStories(): Promise<Array<SuccessStory>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSuccessStories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSuccessStories();
            return result;
        }
    }
    async registerForEvent(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.registerForEvent(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerForEvent(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async submitContact(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContact(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContact(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async submitPartnerInquiry(arg0: string, arg1: string, arg2: string, arg3: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitPartnerInquiry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitPartnerInquiry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async subscribeNewsletter(arg0: string): Promise<{
        __kind__: "ok";
        ok: bigint;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.subscribeNewsletter(arg0);
                return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.subscribeNewsletter(arg0);
            return from_candid_variant_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateAdminPrincipals(arg0: Array<Principal>): Promise<{
        ok: boolean;
        err?: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdminPrincipals(arg0);
                return from_candid_record_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdminPrincipals(arg0);
            return from_candid_record_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBlogPost(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlogPost(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlogPost(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async updateEvent(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvent(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async updateGalleryImage(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGalleryImage(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGalleryImage(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async updateRazorpayKeyId(arg0: string): Promise<{
        ok: boolean;
        err?: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRazorpayKeyId(arg0);
                return from_candid_record_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRazorpayKeyId(arg0);
            return from_candid_record_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSuccessStory(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSuccessStory(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSuccessStory(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateTeamPhotos(arg0: string | null, arg1: string | null): Promise<{
        ok: boolean;
        err?: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTeamPhotos(to_candid_opt_n5(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1));
                return from_candid_record_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTeamPhotos(to_candid_opt_n5(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg1));
            return from_candid_record_n4(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    chairpersonPhotoKey: [] | [string];
    adminPrincipals: Array<Principal>;
    razorpayKeyId: [] | [string];
    treasurerPhotoKey: [] | [string];
}): {
    chairpersonPhotoKey?: string;
    adminPrincipals: Array<Principal>;
    razorpayKeyId?: string;
    treasurerPhotoKey?: string;
} {
    return {
        chairpersonPhotoKey: record_opt_to_undefined(from_candid_opt_n2(_uploadFile, _downloadFile, value.chairpersonPhotoKey)),
        adminPrincipals: value.adminPrincipals,
        razorpayKeyId: record_opt_to_undefined(from_candid_opt_n2(_uploadFile, _downloadFile, value.razorpayKeyId)),
        treasurerPhotoKey: record_opt_to_undefined(from_candid_opt_n2(_uploadFile, _downloadFile, value.treasurerPhotoKey))
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
    err: [] | [string];
}): {
    ok: boolean;
    err?: string;
} {
    return {
        ok: value.ok,
        err: record_opt_to_undefined(from_candid_opt_n2(_uploadFile, _downloadFile, value.err))
    };
}
function from_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: bigint;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: bigint;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
